### ISSUE TITLE
can we have a `x added for construal/supersense label

### ISSUE THREAD

**Issue by dhwang90** [nert-nlp/Xposition#136]

**Comment by ablodge** [comment]
What is ‘x used for?

We can add it in admin.

**Comment by dhwang90** [comment]
It's for Korean pragmatic(-like) postpositions. These straddle both the semantic and pragmatic world. There are true pragmatic postpositional usages too, but those are marked as `d (discourse).

**Comment by dhwang90** [comment]
Currently just a full label for the token. There is no current plan to combine it with a supersense in a construal.

**Comment by nschneid** [comment]
@ablodge How should we add `` `x`` as a special construal? I tried in the admin interface but it wouldn't let me create a URLPath with that as the slug. Is there a mismatch between the admin slug field validation and whatever validation is applied elsewhere?

**Comment by ablodge** [comment]
I'm not sure, but you can import from a list of construals. A csv file with:
```
role_id, function_id, special
0, 0, `x                              
```
should work.

**Comment by nschneid** [comment]
Ah, the import was super easy. @dhwang90, see if it works now.
