### ISSUE TITLE
distinguishing the different [p]s in examples

### ISSUE THREAD

**Issue by dhwang90** [nert-nlp/Xposition#137]
I was wondering if it would be possible to distinguish an adposition for which the examples are for different for other adpositions in the sentence. What I mean is:

Say the page you are adding example to is Agent--Agent and you have a sentence like:
"He was unceremoniously dropped off [p en/by **Locus**] the road [p en/by **Agent**] his angry girlfriend."

Is it possible to make the latter [p] look different from the former? So that viewers know at first look at the adposition we are talking about is the latter one?

Alternatively, the following:
"He was unceremoniously dropped off [p en/by **Locus**] the road [p en/by] his angry girlfriend."

renders the look of the latter [p] in pink rather than the orangy-yellow. But if you click on the link, instead of just staying on the page, it goes to the "by" page. Maybe we could appropriate the underspecified link for examples of the adposition in question and have the link just link ... itself?

**Comment by ablodge** [comment]
You can also do 
"He was unceremoniously dropped off by<sub>[ss Locus]</sub> the road [p en/by Agent] his angry girlfriend."
which specifies the construal of the first _by_ without emphasizing it.

**Comment by nschneid** [comment]
Oh right, for the English guidelines we had supersenses on non-target prepositions displayed as subscripts. Maybe we can have the macros do that automatically? It's a bit of a pain to enter the subscripts in Markdown.

**Comment by ablodge** [comment]
I think we still want most preps to link to usages. I wouldn’t want the macro to over-rely on subscripted construals.

**Comment by ablodge** [comment]
We could do 
"He was unceremoniously dropped off [p en/by Locus]<sub>[ss Locus]</sub> the road [p en/by Agent] his angry girlfriend."
automatically. I'll try it out and see how it looks.
