### ISSUE TITLE
Backslashes showing up

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#160]
http://flat.nert.georgetown.edu/%60d/

I think there was a recent change to Markdown escaping (for backticks?) that may have caused this.

**Comment by lgessler** [comment]
The new markdown engine wants just a single backslash inside macros, not two. The upgrade script should have fixed this (I remember this article looking fine), but you can also fix this manually by just replacing \\_ with \_

**Comment by nschneid** [comment]
Done. A search suggests this was the only problematic article.
