### ISSUE TITLE
History page error

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#166]
http://flat.nert.georgetown.edu/en/streusle4.1/_history/ (from clicking "Changes" on http://flat.nert.georgetown.edu/en/streusle4.1/) gives an Internal Server Error

**Comment by lgessler** [comment]
I think the global url config for corpus sentences is taking precedence. The exception I'm seeing:

```
Exception at /en/streusle4.1/_history/
Sent id "_history" does not exist.
```

**Comment by nschneid** [comment]
In https://github.com/nert-nlp/Xposition/blob/e5bb584217228baea14d27e229089175f4e8a7d1/src/wiki/plugins/metadata/urls.py#L18

would changing `(?P<sent_id>[^/]+)` to `(?P<sent_id>[^/_]+)` fix it? Hopefully there won't be any sentence IDs that start with underscores.
