### ISSUE TITLE
p macro doesn't handle erroneous input

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#179]
E.g. `[p x]` will cause an exception because `x` is not a valid language/preposition combo.

https://github.com/nert-nlp/Xposition/blob/4b7362d45b2ebed35b686d76d5cdb0bfbfc879d4/src/wiki/plugins/macros/mdx/macro.py#L151-L154

Perhaps the right thing to do is display something like INVALID_PREP_NAME.

**Comment by ablodge** [comment]
I handle this and other potential issues by adding try-except blocks around all the macro functions. Currently, an error will result in the text 'Macro Error: please see example usage' instead of crashing the page. 

Any other suggested changes?

**Comment by ablodge** [comment]
Can you give an example input that causes the page to crash on your side?

**Comment by ablodge** [comment]
The input [p in] gives an error and the message displays correctly except for the style.

Do you know why `<span style="color:red">Macro Error: please see example usage</span>` would be displayed as `<span>Macro Error: please see example usage</span>` in the html? Is the css doc overriding my inline style?

**Comment by nschneid** [comment]
If it's not in the HTML it's been stripped out somewhere by the server. Are you replacing article markup? I don't think style attributes are allowed in article markup.

**Comment by lgessler** [comment]
@ablodge depending on where you're doing it I think you need to deserialize it from a string to etree XML objects--[like it's done for construal spans](https://github.com/nert-nlp/Xposition/blob/master/src/wiki/plugins/macros/mdx/macro.py#L472)

**Comment by nschneid** [comment]
fixed in #192
