### ISSUE TITLE
webpage icon

### ISSUE THREAD

**Issue by jenahwang** [nert-nlp/Xposition#182]
Currently the icon on the webpage is something generic. Could you please add a unique icon? It would help me identify the page among open tabs more easily.

This is a low priority request.

**Comment by nschneid** [comment]
You're not seeing the custom icon? It should look like this: 
<img width="83" alt="Screen Shot 2020-04-30 at 3 58 14 PM" src="https://user-images.githubusercontent.com/985263/80753531-69857600-8afb-11ea-91aa-53b9bf97870e.png">

**Comment by nschneid** [comment]
Works in Firefox, not in Chrome

**Comment by nschneid** [comment]
https://stackoverflow.com/questions/25952907/what-is-the-best-practice-for-creating-a-favicon-on-a-web-site

Currently we have a "shortcut icon" PNG. But not all browsers support this.

**Comment by nschneid** [comment]
@ablodge could you try https://realfavicongenerator.net/ with [this large PNG](https://user-images.githubusercontent.com/985263/82508667-c01b1a00-9ad3-11ea-9e8a-9ed3e78d273a.png)?

**Comment by nschneid** [comment]
@nitinvwaran if you're looking for something else to work on, this should be easy

**Comment by nitinvwaran** [comment]
replacing the current png with the favicon alone wasn't enough, following [this gist](https://gist.github.com/iepathos/5350503) also resolved it in chrome. It looks like the below: 
![favicon](https://user-images.githubusercontent.com/35068157/108855675-38df7180-7624-11eb-8a71-4d4c58a28fb0.png)

Raised PR #216 from dev to master
