### ISSUE TITLE
Broken page

### ISSUE THREAD

**Issue by aryamanarora** [nert-nlp/Xposition#189]
http://flat.nert.georgetown.edu/hi/se/Possession--Ancillary/

No idea how this happened. It gave an error message when saving the page so I reloaded. Now I only get:

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

**Comment by nschneid** [comment]
This probably means there was an error in one of your macros. See e.g. #179. Are you able to get back to the edit article page?

**Comment by aryamanarora** [comment]
Oh thanks! I mixed up some arguments to pspecial. It is good now (although an error message would have been useful).
