### ISSUE TITLE
Import Streusle 4.3

### ISSUE THREAD

**Issue by ablodge** [nert-nlp/Xposition#194]
The script for converting connlulex to django models files is here: 

https://github.com/nert-nlp/Xposition/blob/master/scripts/models_for_import.py

Models can then be imported in admin mode assuming django-import-export is installed.

@nschneid If you take a look at the script, you'll see that it's pretty hardcoded for the data from a few years ago. Can you confirm that the new data hasn't changed in terms of format?

**Comment by ablodge** [comment]
To set up STREUSLE json, download the repo and run:
```
python conllulex2json.py streusle.conllulex > streusle.json
python govobj.py streusle.json > streusle.go.json
```

@nschneid What is the significance of "notes" in `streusle.go.notes.json`?

**Comment by nschneid** [comment]
Oh hmm. As I recall there were some per-token annotator comments from the original annotation that aren't part of the official STREUSLE release but that we include in Xposition because they can help explain what's going on.

**Comment by nschneid** [comment]
e.g. http://flat.nert.georgetown.edu/ex/4973/ in the ℹ column

**Comment by ablodge** [comment]
Is there a script that adds notes to the json? I don't see that field in the connlulex or json files.

**Comment by nschneid** [comment]
Your README in the scripts directory mentions annotator_notes.py. Was that a script you wrote?

**Comment by nschneid** [comment]
BTW I think there are sentence-level notes, called `note` in the corpus sentence model, and token-level notes, called `annotator_cluster`.

**Comment by nschneid** [comment]
I forwarded you an email that explains the script/CSV file are in the https://github.com/nert-nlp/streusle/tree/prepare-4.0 branch

**Comment by ablodge** [comment]
I don't see `annotator_notes.py` in either repo, but it should be pretty easy to reverse engineer if you have the original file with notes.

**Comment by ablodge** [comment]
`annotator_notes.py` references files 'prepv-tokens.csv', 'psst-tokens-revisions.csv', 'allbacktick-tokens-revisions.csv', and 'current-psst_20150830.sentnotes.csv'

Do you have these files on hand? Are they still relevant to the new corpus release?

**Comment by nschneid** [comment]
Ah. I forgot the system for collecting notes was so ad hoc. I will have to look to see if there are any spreadsheets with more recent notes.

**Comment by nschneid** [comment]
I can't find any annotator notes for updates executed on STREUSLE 4.1, 4.2, or 4.3. It looks like some of the spreadsheets for updates have color-coding but no textual comments on the decisions.

The only notes I could find were in https://github.com/ryanamannion/streusle/blob/ssupdate/needssupersense.xlsx, and some of these changes may have made their way into 4.2, but AFAICT it was on a case-by-case basis.

So please just use the notes as of the 4.0 release.

(In the future, we should consider a systematic workflow for changes that will allow us to record these notes, perhaps as comments in streusle.conllulex.)

**Comment by ablodge** [comment]
Error while importing Adposition Revision:
```
Line number: 1 - Language matching query does not exist.
my, English, standalone_preposition, Genitive, 0, always_intransitive

Traceback (most recent call last):
File "C:\Users\austi\Anaconda3\lib\site-packages\import_export\resources.py", line 639, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "C:\Users\austi\Anaconda3\lib\site-packages\import_export\resources.py", line 334, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "C:\Users\austi\Anaconda3\lib\site-packages\import_export\resources.py", line 327, in get_instance
return instance_loader.get_instance(row)
File "C:\Users\austi\Anaconda3\lib\site-packages\import_export\instance_loaders.py", line 29, in get_instance
params[field.attribute] = field.clean(row)
File "C:\Users\austi\Anaconda3\lib\site-packages\import_export\fields.py", line 66, in clean
value = self.widget.clean(value, row=data)
File "C:\Users\austi\Anaconda3\lib\site-packages\import_export\widgets.py", line 396, in clean
return self.get_queryset(value, row, *args, **kwargs).get(**{self.field: val})
File "C:\Users\austi\Anaconda3\lib\site-packages\django\db\models\query.py", line 408, in get
self.model._meta.object_name
wiki.plugins.metadata.models.Language.DoesNotExist: Language matching query does not exist.
```

**Comment by ablodge** [comment]
Note: When importing Supersenses, the importer expects an article for each supersense to exist already.

**Comment by nschneid** [comment]
Hmm. Is there a way to just import the corpus examples? We already have the supersenses set up.

**Comment by ablodge** [comment]
Yes. I'm just working through the steps in https://github.com/nert-nlp/Xposition/tree/master/scripts to load models from scratch without the current database.

**Comment by ablodge** [comment]
![image](https://user-images.githubusercontent.com/11709538/88835136-da900480-d1a2-11ea-9e8c-73ad2f8db2fc.png)
Another unexpected problem. This is encoded in utf8.

**Comment by ablodge** [comment]
Error `AttributeError at /admin/metadata/corpussentence/import/
module 'tablib.formats._xls' has no attribute 'title'` in `C:\Users\austi\Anaconda3\lib\site-packages\import_export\formats\base_formats.py in get_title
        return self.get_format().title` while trying to import corpus sentences.

**Comment by ablodge** [comment]
Error: `InvalidDimensions encountered while trying to read file: corpus_sentences.tsv1` displayed with no stack trace when trying to import corpus sentences.

**Comment by ablodge** [comment]
Related: Does the class `CorpusSentenceResource` need to specify a corpus version. It seems to be missing, which may cause problems later.

**Comment by ablodge** [comment]
When unpacking xposition database file with sqlite, I get the error:
```
Error: near line 3: file is not a database
Error: near line 9: file is not a database
Error: near line 10: file is not a database
Error: near line 11: file is not a database
...
```

**Comment by nschneid** [comment]
Hmm, maybe `.read` requires a valid database to exist, whereas the `sqlite3 x.db < x.sql` option does not.

**Comment by ablodge** [comment]
Alright, the import is almost working, but there are a few issues. I can convert streusle data to json and tsv files, and I can import corpus sentences for different versions of the same corpus, but:
- [ ] New corpus sentences need to have different ids than the ones in the database. This is because annotations are associated with a sentence which is identified uniquely by an id, but different corpus versions can have different annotations. To import import two sentneces and have them stored as seperate objects, they need different ids. We could do something like 'streusle4.3:reviews-001325-0004'
- [ ] Generating json and tsv files has to be done several times because of dependencies from Usage to Construal and Adposition, PTokenAnnotation to Usage, etc. I'm trying to make this clearer in the code and instructions to make it easier to just import sentences, and annotations, rather than needing to start from scratch.
- [ ] I'm having trouble getting the .db file to work locally. See #196

**Comment by nschneid** [comment]
> New corpus sentences need to have different ids than the ones in the database. This is because annotations are associated with a sentence which is identified uniquely by an id, but different corpus versions can have different annotations. To import import two sentneces and have them stored as seperate objects, they need different ids.

I'm not sure why they would need different `sent_id`s: the `CorpusSentence` model specifies

```py
unique_together = [('corpus', 'sent_id')]
```

which says only that each `sent_id` *within* a corpus instance has to be unique. Each instance of a model has an automatic ID assigned (I think it's called `.pk` for primary key).

**Comment by ablodge** [comment]
In that case, there is a problem with the importer. Whenever importing a new corpus sentence that has the same sent_id as an existing sentence, the importer overwrites the data in the existing sentence instead of creating a new object, and this is true even if the corpus versions are different.

**Comment by nschneid** [comment]
Maybe due to how admin.py is configured? Could be related to https://github.com/nert-nlp/Xposition/blob/5168edd9664ecc7683a75322695e273dd2a561a2/src/wiki/plugins/metadata/admin.py#L196
though I don't know exactly what `import_id_fields` does.

**Comment by nschneid** [comment]
(Maybe `import_id_fields = ('corpus', 'sent_id')` would do the trick, as these are the fields that uniquely define the CorpusSentence instances?)

**Comment by ablodge** [comment]
When import PTokenAnnotations I get the following:
![image](https://user-images.githubusercontent.com/11709538/89671619-4bc16d00-d8b1-11ea-9c30-0299b9163e85.png)

**Comment by ablodge** [comment]
This is strange because (1) the code does check to see if the sentence is unique ([here](https://github.com/nert-nlp/Xposition/blob/afbcff5c6e6fff046102214841c3ffc8bef6c9a7/src/wiki/plugins/metadata/admin.py#L35)), and (2) PTokenAnnotation has no feature called `sentence_id`. It's just called `sentence`. So I'm wondering how this error was generated.

**Comment by nschneid** [comment]
Unique constraints are enforced at the database level, so `sentence_id` may be the underlying name in the database. Look at the database table schemas to see where this might be coming from and then figure out if the model is correct.

**Comment by ablodge** [comment]
The model does use `sentence_id` as an attribute in the database. 

```
CREATE INDEX "metadata_ptokenannotation_adposition_id_0858ff6a" ON "metadata_ptokenannotation" ("adposition_id");
CREATE INDEX "metadata_ptokenannotation_construal_id_0cc05c85" ON "metadata_ptokenannotation" ("construal_id");
CREATE INDEX "metadata_ptokenannotation_sentence_id_b92bfeeb" ON "metadata_ptokenannotation" ("sentence_id");
CREATE INDEX "metadata_ptokenannotation_usage_id_eaff3eb9" ON "metadata_ptokenannotation" ("usage_id");
CREATE UNIQUE INDEX "metadata_ptokenannotation_sentence_id_token_indices_d911a308_uniq" ON "metadata_ptokenannotation" ("sentence_id", "token_indices");
```

**Comment by ablodge** [comment]
I'm checking to see if the 4.3 data is internally consistent (if every annotation has a unique sent_id, toke_inices pair). If not, then that's easier to fix. It would also explain why import sentences didn't cause a unique constraint error but importing annotations did.

**Comment by ablodge** [comment]
It's been replaced by a new error:
![image](https://user-images.githubusercontent.com/11709538/89683119-ef1c7d00-d8c5-11ea-93f0-acd0776c9727.png)

**Comment by nschneid** [comment]
Well, not NULL. :) What is it currently for that token in the database (old version of the corpus)?

**Comment by ablodge** [comment]
All the different steps work! I'll make a pull request and review the changes.
