### ISSUE TITLE
Expose typo/abbreviation information for PTokenAnnotations

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#201]
`is_typo`, `is_abbr` fields are not used when displaying annotations. They could be flagged with an icon.

**Comment by nitinvwaran** [comment]
Added these columns in the Token Annotation table, some screenshots of what it looks like are below:

![new_cols_header](https://user-images.githubusercontent.com/35068157/108621906-8d41f000-7470-11eb-8902-0b17fe88d85b.png)
![new_columns](https://user-images.githubusercontent.com/35068157/108621908-903ce080-7470-11eb-82bc-82b96e775eaa.png)

**Comment by nschneid** [comment]
Thanks. Why is the "out of" example showing up as a typo & abbreviation?

**Comment by nitinvwaran** [comment]
That's because I manually edited the flag in the backend , to test whether it would show up in the wiki! In production the original values were both 0

**Comment by nschneid** [comment]
Oh good. Could you change the header from "Abbreviation?" to "Abbrev?" Just so it's shorter.

**Comment by nitinvwaran** [comment]
This is done and checked into dev:

![header-2](https://user-images.githubusercontent.com/35068157/108628739-76fb5a80-7497-11eb-8243-f9b9d23b0a15.png)

**Comment by nschneid** [comment]
Excellent! Could you make a PR?
