### ISSUE TITLE
Parallel corpora

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#202]
- Models: Currently the `PTokenAnnotation` model simply has an `is_parallel` field, but no way to indicate how to find the parallel annotation. A many-to-many field could work in theory, but could make import difficult. (Is there a way for the imported TSV file to specify aligned token offsets and have admin.py look up records?) Parallel corpora should probably be marked as such at the corpus and sentence levels, too.

- UI: How to display parallel corpora/sentences/token annotations?

**Comment by nitinvwaran** [comment]
I think #234 has mostly handled this? But it hasn't done parallel corpora. Should a new alignment be created for parallel corpora (or would this maybe be too much?)

**Comment by nschneid** [comment]
Too much I think. We can always edit corpus description pages to list parallel corpora.
