### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#211]
- add tqdm
- try Pillow>=7.1.0

**Comment by nitinvwaran** [comment]
i can take a look at this, i'm just not fully sure how to test Pillow in the system , i understand it to be a python-based image processing library

**Comment by nschneid** [comment]
Yeah I just want to make sure it doesn't break Xposition due to an incompatibility with something else

**Comment by nitinvwaran** [comment]
Tested this with Pillow == 8.1.0 and added pillow>=7.1.0 and tqdm to requirements.txt. Tested the wiki pages including adding category, changing meta-data, and loading the supersense, construal, and a language page, with no issues.

I created a new PR #215

**Comment by nschneid** [comment]
Thanks!
