### ISSUE TITLE
Database integrity error: word_gloss should not be null

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#235]
Apparently the Django ORM doesn't distinguish database values NULL and empty string, mapping them both to Python `None`. The import scripts have been assigning the single-space string `' '` as an empty value to fields defined with `blank=True` but not `null=True`. But somehow there are still `word_gloss` values in the database for which this needs to be done.

**Comment by nschneid** [comment]
I found the underlying issue: it is that the type of the field is `StringListField`—it expects a gloss for each word in the sentence:

https://github.com/nert-nlp/Xposition/blob/1e09ad6c821f429d95017231065cc9f830e0264c/src/wiki/plugins/metadata/models.py#L898

For clarity, change "Word Gloss" to "Word Glosses".

Note that `blank=True` is correct: it allows the value to be optional in forms. https://stackoverflow.com/a/8609425 discusses how `null=True` is not allowed on text fields. (Maybe note this in a comment)

Fixing this requires modifying how `StringListField` handles empty/all-space strings:

https://github.com/nert-nlp/Xposition/blob/1e09ad6c821f429d95017231065cc9f830e0264c/src/wiki/plugins/metadata/models.py#L37-L70

In particular, 63 seems to disallow any falsey Python value from being serialized. It should probably have `if value is None: return ''`. Or maybe any falsey Python value (`None`, empty string as input by a form, or empty list?) should serialize as `''`. Line 54 deserializes, and `return` should be made more explicit as `return None`.

For importing corpora, replace

https://github.com/nert-nlp/Xposition/blob/1e09ad6c821f429d95017231065cc9f830e0264c/xposition/scripts/new_corpus.py#L61

to assign `None`.

**Comment by nschneid** [comment]
(In the meantime, when editing db objects in the shell, the workaround of setting `word_gloss = ' '` before calling `save()` will avoid the error.)

**Comment by lgessler** [comment]
That fix plan seems OK, but why not set `null=True` on the field? From what I read in that stackoverflow discussion, it seems like the main reason is that this means in principle the DB could be using both `""` and `NULL` in the column, but if the ORM conflates them anyway then this doesn't seem like an issue, right?
