### ISSUE TITLE
Internal server error when clicking through to corpus examples for Theme

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#236]
- http://flat.nert.georgetown.edu/_table/supersense/62/?perpage=100: error
- http://flat.nert.georgetown.edu/_table/supersense/62/: works OK, but http://flat.nert.georgetown.edu/_table/supersense/62/?page=4 causes the error (so it is an entry between 76 and 100)

**Comment by nschneid** [comment]
This is triggered by https://github.com/nert-nlp/Xposition/blob/b8b321e4ff201562a7cb8823dee2dd197777cd65/src/wiki/plugins/metadata/tables.py#L73 and appears to reflect a mismatch between the token annotation and the associated sentence object. Maybe a sentence tokenization issue on import.

```py
$ python manage.py shell
>>> from wiki.plugins.metadata.models import PTokenAnnotation
>>> for x in PTokenAnnotation.objects.all():
...   indices = x.main_subtoken_indices
...   assert indices[-1]<=len(x.sentence.tokens)
...
Traceback (most recent call last):
  File "<console>", line 3, in <module>
AssertionError
>>> x
<PTokenAnnotation: 's : pastrie2.0: german-b7b4ea19-f3c6-0ca9-f523-ae25f9908c04-07>
>>> x.main_subtoken_indices
[12]
>>> x.sentence
<CorpusSentence: pastrie2.0: german-b7b4ea19-f3c6-0ca9-f523-ae25f9908c04-07>
>>> x.sentence.text
'Looks pretty Nazi-like to me'
>>> x.sentence.tokens
['Looks', 'pretty', 'Nazi', '-', 'like', 'to', 'me']
>>> x.html
'<a href="/ex/15948/" class="exnum">(15948)</a>'
```

This particular example is http://flat.nert.georgetown.edu/ex/15948/

**Comment by nschneid** [comment]
Looking at pastrie.conllulex, it seems we have two sentences with the same ID. The token annotation belongs in the 1st one but the sentence tokens got clobbered by the 2nd. :(

Opened an issue for the data: nert-nlp/pastrie#16

The import code should probably

- [ ] Check uniqueness of sentence IDs
- [ ] Check that `indices[-1]<=len(x.sentence.tokens)` as above

**Comment by nschneid** [comment]
Resolved the errors by manually editing the db to match corrected PASTRIE 2.0.1. But updating the import code is a good idea.

**Comment by lgessler** [comment]
cf. nert-nlp/conllulex#1

**Comment by nschneid** [comment]
Additional validation in the import code is WONTFIX but let's add a reminder in the README to run the validator before import.
