### ISSUE TITLE
Better error handling for corpus displays

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#238]
Currently this exception (causing an Internal Server Error) is triggered not only when providing an invalid sentence ID in the URL, but also when providing a valid sentence ID with no annotated tokens (e.g. http://flat.nert.georgetown.edu/en/pastrie2.0.1/german-cfa8fd9b-a8c2-9379-c816-a94b0e42b253-02/):

https://github.com/nert-nlp/Xposition/blob/1e09ad6c821f429d95017231065cc9f830e0264c/src/wiki/plugins/metadata/templatetags/metadata_tags.py#L210-L212

Ideally (a) such errors should be displayed as messages in the wiki, and (b) it should be possible to display a sentence without annotations.

**Comment by lgessler** [comment]
https://docs.djangoproject.com/en/3.2/howto/error-reporting/

**Comment by lgessler** [comment]
This addresses (b) but not (a), to be clear. I think if we want to tackle (a) as well we should take a more holistic look at what happens when URLs fail to describe a real resource and apply a consistent solution to all possible cases

**Comment by nschneid** [comment]
Fixed on the server. Providing an invalid sentence ID displays a blank page, which is at least better than an internal server error.
