### ISSUE TITLE
Sentence view: concordance columns should be wider

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#242]
The columns to the left and right of the target token should be widened so the table doesn't take up so much vertical space:
http://www.xposition.org/en/pastrie2.0.1/english-00f24603-8295-1fe0-52c5-53b5d2f74429-01/
http://www.xposition.org/ex/16394/

**Comment by nschneid** [comment]
How it looks now:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/985263/183805757-199e4f08-8c61-4a4c-bd46-d644315544bd.png">

**Comment by nitinvwaran** [comment]
Tweaked some css and html, here are some updated screenshots. The grids can be made wider if needed.
![sentence_view_1](https://user-images.githubusercontent.com/35068157/186501157-6df010af-ff2a-4f14-a56a-67b69453e385.png)

![token_view_1](https://user-images.githubusercontent.com/35068157/186501180-c28ebd09-b9b3-4faf-a1b1-83f025a3a0dc.png)

![token_view_2](https://user-images.githubusercontent.com/35068157/186501190-9d34557b-da3f-46b2-9fea-125443173297.png)

**Comment by nschneid** [comment]
The above commit applies the `lcontext` and `rcontext` classes activating style rules in metadata.css.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/985263/204439023-8cded9d2-aa16-449c-9379-2d424ae1810b.png">
