### ISSUE TITLE
Update django-wiki

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/Xposition#45]
Xposition was forked from the [django-wiki](https://github.com/django-wiki/) platform, which has since been updated with additional functionality including a global history plugin, which would be nice to have. I've rebased the Xposition repository to reflect the fact that it was forked and created a djangowiki-sync branch that pulls in the updates. But I haven't figured out how to get it running (probably requires configuration changes and/or database upgrade). @ablodge if you have time, you may be able to figure it out faster than I can. Nearly all of the Xposition-specific customizations are in the "metadata" plugin to keep them separate from django-wiki code.

**Comment by ablodge** [comment]
See [Release notes](http://django-wiki.readthedocs.io/en/latest/release_notes.html) under Upgrading. It doesn't say anything about adapting code.

**Comment by ablodge** [comment]
I'm trying this out locally. Should I add settings to `INSTALLED_APPS` and `TEMPLATES` from their [installation guide](http://django-wiki.readthedocs.io/en/latest/installation.html)?

**Comment by ablodge** [comment]
I'm getting an error
`ModuleNotFoundError: No module named 'wiki.apps.WikiConfig'; 'wiki.apps' is not a package`

**Comment by ablodge** [comment]
Looking at your branch djangowiki-sync, when I run `pip install wiki`, I get a warning:
`django-categories 1.6 has requirement django-mptt<0.10,>=0.9.0, but you'll have django-mptt 0.8.7 which is incompatible.`
This may be the cause of some of the `INSTALLED_APPS` not being understood. When I try to migrate, I get `ModuleNotFoundError: No module named 'wiki.plugins.categories'`. I'll look into django-categories to see if there is a compatible version.

**Comment by nschneid** [comment]
Looks like Django 2 support for django-wiki is still in alpha: https://github.com/django-wiki/django-wiki/releases

**Comment by ablodge** [comment]
Okay, I pulled from upstream on django-wiki as described [here](https://help.github.com/articles/syncing-a-fork/).

These files have conflicts:
- [ ] src\wiki\admin.py
- [ ] src\wiki\urls.py
- [ ] testproject\testproject\settings\base.py
- [ ] testproject\testproject\settings\dev.py
- [ ] testproject\testproject\urls.py
- [ ] wiki\core\markdown\mdx\codehilite.py
- [ ] wiki\plugins\macros\mdx\macro.py

**Comment by nschneid** [comment]
I don't know about the Markdown stuff, but for the others it's probably possible to factor out our customizations so they'll be in separate files and not conflict with upstream.

We should probably rename testproject/testproject to xposition/xp or similar. I don't know how many files this would affect.

What about views/article.py? I think we customized that too. But it would be better to move the customization to a MetadataArticleView subclass in wiki.plugins.metadata.views that is substituted for the regular ArticleView by wiki.plugins.metadata.urls.XpositionURLPatterns.

**Comment by ablodge** [comment]
Where should customizations in base.py, dev.py, and testproject\urls.py be moved?

**Comment by nschneid** [comment]
> Where should customizations in base.py, dev.py, and testproject\urls.py be moved?

What I think makes sense is to have the xposition directory contain what we previously had in testproject. Everything under testproject should be seen as a template for an actual project.

**Comment by ablodge** [comment]
The update created a folder src/wiki where almost everything was moved automatically. What's left are _pyache_ files, codehilite.py, and macro.py.

**Comment by ablodge** [comment]
Should we move the content of wiki over to src/wiki?

**Comment by nschneid** [comment]
I think we should mirror the upstream branch except for adding a few custom files.

**Comment by ablodge** [comment]
Are macro.py and codehilight.py custom files? Can I just move them into the directory or do I need to add them to some special location?

**Comment by nschneid** [comment]
Hmm. macro.py contains the custom macros—can those be factored out into another file in subclasses of `MacroExtension` and `MacroPreprocessor`, such that the metadata plugin will automatically provide all the macros?

Our only customization in codehilite.py was removing a warning message. Let's discard that file for now and see if the warning message still occurs in the synced version.

**Comment by ablodge** [comment]
What are the \_\_pyache\_\_ files and do we need them?

> can those be factored out into another file in subclasses of MacroExtension and MacroPreprocessor, such that the metadata plugin will automatically provide all the macros?

I'm not sure, but where would the customized file go?

**Comment by nschneid** [comment]
> What are the __pyache__ files and do we need them?

No, let's take them out of the repository: https://stackoverflow.com/a/16869074

> I'm not sure, but where would the customized file go?

Ideally under the metadata directory.
